language: node_js
node_js:
  - "node"
  - "iojs"
  - "6"
  - "5"
  - "4"
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS mlustats;" -uroot
  - gem install sass
script: "grunt ci"
